fix: the `debug` package errors
Errors related to different ways the `debug` package is consumed:
```
[eslint] The requested module 'debug' does not provide an export named 'default'
```
and
```
Uncaught Error: Cannot find module 'debug'
```

Let's introduce commonjs and esm versions of imports in our dummy package.