fix: make gene and cds ids distinct
We create virtual genes and CDSes if one of those feature types are missing in the input annotation, so a gene and its child CDSes may end up having the same IDs, i.e. non-unique IDs. This causes GFF validation failure:

```
$ gt gff3validator nextclade.gff
error: the multi-feature with ID "<some_id>" on line 3 in file "nextclade.gff" has a different type than its counterpart on line 2 
```

Let's make IDs of genes and their corresponding CDS distinct by prefixing feature type.