feat: upgrade auspice and add polyfills
This upgrades auspice again to v2.55.0, while avoiding crash with error

```
choose-branch-labelling.js:116 Uncaught TypeError: (intermediate value).union is not a function
    at Function.eval [as mapToProps] (choose-branch-labelling.js:116:73)
```
[here](https://github.com/nextstrain/auspice/blob/5afe5814b7304b65b3856df136ceeac88cf4690e/src/components/controls/choose-branch-labelling.js#L15-L16) due to `Set.union()` not available in older browsers ([caniuse](https://caniuse.com/mdn-javascript_builtins_set_union), [mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/union))

The root of the problem, I think, was migration to Next.js 12 along with swc and removing babel. I am not sure if babel would correctly polyfill this, but I believe that env preset would have added relevant core-js fills. The current setup does not. There is only a [handful of polyfills applied](https://nextjs.org/docs/architecture/supported-browsers) by Next.js nowadays.

Considering that we might have other modern code in the codebase which is also crashing on older browsers, I chose to include `core-js` explicitly to be safe. It adds a lot of code to the bundle though and all other drawbacks of polyfills.

Maybe newer versions of Next.js improve situation (I doubt it, they've been pitching "modern" browsers for years now), or maybe there are additional tools for swc similar to what [babel-preset-env](https://babeljs.io/docs/babel-preset-env) offered, then explicit import of `core-js` can be reconsidered.