fix(dev): Use a buildx builder instance we control instead of the default
We require the "docker-container" driver (via options we pass to `docker
buildx build`, e.g. --cache-to) but the default builder instance may use
the "docker" driver, leading to errors on dev machines like:

    ERROR: cache export feature is currently not supported for docker
    driver. Please switch to a different driver (eg. "docker buildx
    create --use")

Being explicit about our builder avoids that.

This same pattern is used in nextstrain/docker-base's devel/build.¹

¹ <https://github.com/nextstrain/docker-base/commit/fac834e5>
  <https://github.com/nextstrain/docker-base/blob/0acdc799/devel/build#L48-L56>

Related-to: <https://github.com/nextstrain/nextclade/pull/1529#issuecomment-2414459858>